name: Run stuff
on: [push]
jobs:
  Run-Julia-ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'      
      - uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
      - run: julia -e 'println("Hello, World!")'
