name: Run stuff
on: [schedule]
jobs:
  Run-Julia-ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - run: julia -e 'println("Hello, World!")'
